### ISSUE TITLE
ESP32 code will build but not Flash or erase flash

### ISSUE THREAD

**Issue by Jhews6** [Topographic-Robot/Documentation#10]
When trying to flash onto the board the message "A fatal error occurred: Failed to connect to Espressif device: Wrong boot mode detected (0x13)! The chip needs to be in download mode." appears.

**Comment by Jhews6** [comment]
Hold the boot button down while flashing or erasing flash, ESP is so silly lol. The boot button is on the side of the usb port.

**Comment by bsikar** [comment]
bro did not think esp was silly in the moment
